# docker-compose.yaml for nodered


version: '3.7'
services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: always
    #ports:
    #  - 8002:1880
    volumes:
      - /var/homeautomation/nodered/volumes/node-red-data:/data
    environment:
      - TZ=Europe/Berlin
    user: 0:0

    networks:
      bitwarden:
        ipv4_address: 10.10.60.1

networks:
  bitwarden:
    name: homeautomation
    external: true