# docker-compose.yaml for bitwarden
# inspired by: https://github.com/CVJoint/docker-compose/blob/master/ymlfiles/bitwarden.yml

version: '3.7'
services:
  bitwarden:
    container_name: nodered
    image: bitwardenrs/server
    restart: always
    ports:
      - 8002:1880
    volumes:
      - /var/homeautomation/bitwarden/bwdata:/data
    networks:
      bitwarden:
        ipv4_address: 10.0.60.1

networks:
  bitwarden:
    name: homeautomation
    external: true