version: '2.1'
services:
  vpn:
    cap_add:
     - NET_ADMIN
    #image: project31/aarch64-docker-openvpn
    image: nubacuk/docker-openvpn:aarch64
    container_name: vpn
    ports:
     - "10000:1194/tcp"
    restart: unless-stopped
    volumes:
     - /var/homeautomation/vpn/volumes/openvpn/conf:/etc/openvpn


    networks:
      vpn:
        ipv4_address: 10.10.40.1




networks:
  vpn:
    name: homeautomation
    external: true