# docker-compose.yaml for Unifi

version: "2.1"
services:
  unifi:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /var/homeautomation/unifi/volumes/unifi-config:/config
    ports:
      - 9002:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      #- 1900:1900/udp #optional
      #- 8843:8843 #optional for Guest Portal https
      #- 8880:8880 #optional for Guest Portal http
      #- 6789:6789 #optional for Speedtest
      #- 5514:5514/udp #optional
    restart: unless-stopped
    networks:
      unifi:
        ipv4_address: 10.10.90.1
  

networks:
  unifi:
    name: homeautomation
    external: true

