# docker-compose.yaml for $application
# inspired by: https://mindsers.blog/post/https-using-nginx-certbot-docker/


version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest     
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/homeautomation/nginx/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /var/homeautomation/nginx/volumes/certbot/www:/var/www/certbot
      - /var/homeautomation/nginx/volumes/certbot/conf:/etc/nginx/ssl
    networks:
      nginx:
        ipv4_address: 10.0.10.1
  certbot:
    container_name: certbot
    image: certbot/certbot:arm64v8-latest
    restart: unless-stopped
    volumes:
      - /var/homeautomation/nginx/volumes/certbot/www:/var/www/certbot
      - /var/homeautomation/nginx/volumes/certbot/conf:/etc/letsencrypt
    command: "certonly --standalone -d tomasz.app -d bitwarden.tomasz.app --force-renewal"
    networks:
      nginx:
        ipv4_address: 10.0.10.20

networks:
  nginx:
    name: homeautomation
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/16"