# docker-compose.yaml for $application
# inspired by: https://mindsers.blog/post/https-using-nginx-certbot-docker/


version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest     
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /var/homeautomation/nginx/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /var/homeautomation/nginx/volumes/certbot/www:/var/www/certbot
      - /var/homeautomation/nginx/volumes/certbot/conf:/etc/nginx/ssl
    networks:
      nginx:
        ipv4_address: 10.10.10.1


networks:
  nginx:
    name: homeautomation
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/16"