# docker-compose.yaml for grafana
# Insired By: https://grafana.com/docs/grafana/v9.0/setup-grafana/installation/docker/
# https://grafana.com/docs/grafana/v9.0/setup-grafana/configure-docker/

version: '3.7'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    #ports:
    #  - 8004:3000
    user: "0:0"
    environment:
      #- GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource    # Automativaly install Plugins
      - GF_SECURITY_ADMIN_PASSWORD:${WEBPASSWORD}
    
    volumes:
      - /var/homeautomation/grafana/volumes/grafana-data:/var/lib/grafana
    
    restart: unless-stopped
    networks:
      grafana:
        ipv4_address: 10.10.80.1
  

networks:
  grafana:
    name: homeautomation
    external: true

