version: '2'
services:
  vpn:
    cap_add:
     - NET_ADMIN
    #image: project31/aarch64-docker-openvpn
    image: nubacuk/docker-openvpn:aarch64
    container_name: vpn
    ports:
     - "443:1194/tcp"
    restart: unless-stopped
    volumes:
     - /var/homeautomation/vpn/volumes/openvpn/conf:/etc/openvpn


    networks:
      vpn:
        ipv4_address: 10.0.30.10




networks:
  vpn:
    ipam:
      driver: default
      config:
        - subnet: "10.0.30.0/24"