version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: project31/aarch64-docker-openvpn
    container_name: openvpn
    ports:
     - "443:1194/udp"
    restart: unless-stopped
    volumes:
     - /var/homeautomation/vpn/volumes/openvpn/conf:/etc/openvpn


    networks:
      vpn:
        ipv4_address: 10.0.30.10




networks:
  vpn:
    ipam:
      driver: default
      config:
        - subnet: "10.0.30.0/24"