# docker-compose.yaml for database (mysql)


# Use root/example as user/password credentials
version: '3.7'

services:

  database:
    container_name: database
    # user: "0:0"
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 10002:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    volumes:
      - /var/homeautomation/database/volumes/database-data:/var/lib/mysql

    networks:
      database:
        ipv4_address: 10.0.70.1

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8003:8080

    networks:
      database:
        ipv4_address: 10.0.70.2



networks:
  database:
    name: homeautomation
    external: true

