version: "3.7"

# Inspired By:
# https://www.youtube.com/watch?v=DM65_JyGxCo
# https://github.com/pi-hole/docker-pi-hole#readme
# https://hub.docker.com/r/ubuntu/bind9
#
#


# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8000:80/tcp"
    volumes:
      - '/var/homeautomation/pihole/volumes/pihole/etc-pihole:/etc/pihole'
      - '/var/homeautomation/pihole/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    environment:
      TZ: 'Europe/Berlin'
      PIHOLE_DNS_: '10.10.30.2'
      WEBPASSWORD: ${WEBPASSWORD}
      VIRTUAL_HOST: pihole.${EXTERNAL_DOMAIN}
    # Volumes store your data between container upgrades
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)  
    depends_on:
      - bind9
    
    networks:
      pihole:
        ipv4_address: 10.10.30.1
        
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    restart: unless-stopped
    volumes:
      - /var/homeautomation/pihole/volumes/bind9/etc-bind:/etc/bind/:Z
      #- /var/homeautomation/pihole/volumes/bind9/var-cache-bind:/var/cache/bind:Z
      - /var/homeautomation/pihole/volumes/bind9/var-lib-bind:/var/lib/bind:Z
    environment:
      TZ: 'Europe/Berlin'
      
    networks:
      pihole:
        ipv4_address: 10.10.30.2
   
networks:
  pihole:
    name: homeautomation
    external: true
