# docker-compose.yaml for bitwarden
# inspired by: https://github.com/CVJoint/docker-compose/blob/master/ymlfiles/bitwarden.yml

version: '3'
services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - /var/homeautomation/bitwarden/bwdata:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
      DOMAIN: https://bitwarden.${DOMAINNAME}
    networks:
      bitwarden:
        ipv4_address: 10.0.30.10